apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: FastListIteration
  annotations:
    github.com/project-slug: cbdurietz/FastListIteration
spec:
  type: other
  lifecycle: unknown
  owner: guests
